---

- name: Download AgentConfig.xml from target.
  ansible.builtin.fetch:
    src: '{{ wincollect_agent_install_dir }}\config\AgentConfig.xml'
    dest: "/var/tmp/{{ 1000 | random | hash('md5') }}"
    flat: true
  changed_when: false
  register: agentconfig_fetched

- name: Custom query handling.
  block:
    - name: Create temporary template file.
      ansible.builtin.tempfile:
        state: file
      register: temporary_query_template
      delegate_to: localhost
      changed_when: false

    - name: Create temporary template from query variables.
      ansible.builtin.template:
        src: tmplt_CustomQuery.xml.j2
        dest: "{{ temporary_query_template.path }}"
      delegate_to: localhost
      changed_when: false
      loop: "{{ wincollect_agent_custom_querys }}"

    - name: Encode temporary_query_template to base64.
      ansible.builtin.slurp:
        src: "{{ temporary_query_template.path }}"
      register: temporary_query_template_b64
      delegate_to: localhost

    - name: Remove temporary query template.
      ansible.builtin.file:
        path: "{{ temporary_query_template.path }}"
        state: absent
      changed_when: false
      delegate_to: localhost

- name: Extract XML data blocks.
  block:
    - name: Extract DeviceWindowsLog from AgentConfig.xml
      ansible.builtin.shell: cat "{{ agentconfig_fetched.dest }}" | awk '/<Service version="[0-9.]*" classification="Service" type="DeviceType" module="DeviceWindowsLog" name="DeviceWindowsLog">/,/<\/Service>/' | tr -d "\r"
      register: devicewindowslog_var
      changed_when: false
      delegate_to: localhost

    - name: Extract DestinationManager from AgentConfig.xml.
      ansible.builtin.shell: cat "{{ agentconfig_fetched.dest }}" | awk '/<Service version="[0-9.]*" classification="Service" type="Service" module="WinCollectPlugin" name="DestinationManager">/,/<\/Service>/' | tr -d "\r"
      register: destinationmanager_var
      changed_when: false
      delegate_to: localhost

    - name: Extract PayloadRouter from AgentConfig.xml.
      ansible.builtin.shell: cat "{{ agentconfig_fetched.dest }}" | awk '/<Service classification="Service" type="Service" version="[0-9.]*" module="Routing" name="PayloadRouter">/,/<\/Service>/' | tr -d "\r"
      register: payloadrouter_var
      changed_when: false
      delegate_to: localhost

    - name: Extract AgentCore from AgentConfig.xml.
      ansible.builtin.shell: cat "{{ agentconfig_fetched.dest }}" | awk '/<Service classification="Static" type="Service" version="[0-9.]*" module="AgentCore" name="AgentCore">/,/<\/Service>/' | tr -d "\r"
      register: agentcore_var
      changed_when: false
      delegate_to: localhost

- name: Delete fetched AgentConfig.xml file.
  ansible.builtin.file:
    path: "{{ agentconfig_fetched.dest }}"
    state: absent
  changed_when: false
  delegate_to: localhost

- name: PayloadRouter block.
  block:
    - name: Create temporary PayloadRouter XML.
      ansible.builtin.copy:
        dest: "/var/tmp/{{ 1000 | random | hash('md5') }}"
        content: "{{ payloadrouter_var.stdout }}"
      register: payloadrouter_section
      changed_when: false
      delegate_to: localhost

    - name: Check if PayloadRouter configuration needs patching.
      ansible.builtin.template:
        src: tmplt_PayloadRouter.xml.j2
        dest: "{{ payloadrouter_section.dest }}"
      check_mode: true
      delegate_to: localhost
      register: payloadrouter_needs_patching

    - name: Delete temporary PayloadRouter XML.
      ansible.builtin.file:
        path: "{{ payloadrouter_section.dest }}"
        state: absent
      changed_when: false
      delegate_to: localhost

    - name: Create PayloadRouter patch template.
      become: true
      ansible.windows.win_template:
        src: tmplt_PayloadRouter.xml.j2
        dest: '{{ wincollect_agent_install_dir }}\patch\service_PayloadRouter.xml'
      when: payloadrouter_needs_patching.changed

- name: AgentCore block.
  block:
    - name: Create temporary AgentCore XML.
      ansible.builtin.copy:
        dest: "/var/tmp/{{ 1000 | random | hash('md5') }}"
        content: "{{ agentcore_var.stdout }}"
      register: agentcore_section
      changed_when: false
      delegate_to: localhost

    - name: Check if AgentCore configuration needs patching.
      ansible.builtin.template:
        src: tmplt_AgentCore.xml.j2
        dest: "{{ agentcore_section.dest }}"
      check_mode: true
      delegate_to: localhost
      register: agentcore_needs_patching

    - name: Delete temporary AgentCore XML.
      ansible.builtin.file:
        path: "{{ agentcore_section.dest }}"
        state: absent
      changed_when: false
      delegate_to: localhost

    - name: Create AgentCore patch template.
      become: true
      ansible.windows.win_template:
        src: tmplt_AgentCore.xml.j2
        dest: '{{ wincollect_agent_install_dir }}\patch\service_AgentCore.xml'
      when: agentcore_needs_patching.changed

- name: DestinationManager block.
  block:
    - name: Create temporary DestinationManager XML.
      ansible.builtin.copy:
        dest: "/var/tmp/{{ 1000 | random | hash('md5') }}"
        content: "{{ destinationmanager_var.stdout }}"
      register: destinationmanager_section
      changed_when: false
      delegate_to: localhost

    - name: Check if DestinationManager configuration needs patching.
      ansible.builtin.template:
        src: tmplt_DestinationManager.xml.j2
        dest: "{{ destinationmanager_section.dest }}"
      check_mode: true
      delegate_to: localhost
      register: destinationmanager_needs_patching

    - name: Delete temporary DestinationManager XML.
      ansible.builtin.file:
        path: "{{ destinationmanager_section.dest }}"
        state: absent
      changed_when: false
      delegate_to: localhost

    - name: Create DestinationManager patch template.
      become: true
      ansible.windows.win_template:
        src: tmplt_DestinationManager.xml.j2
        dest: '{{ wincollect_agent_install_dir }}\patch\service_DestinationManager.xml'
      when: destinationmanager_needs_patching.changed

- name: DeviceWindowsLog block.
  block:
    - name: Create temporary WinEvent XML.
      ansible.builtin.copy:
        dest: "/var/tmp/{{ 1000 | random | hash('md5') }}"
        content: "{{ devicewindowslog_var.stdout }}"
      register: winevent_section
      changed_when: false
      delegate_to: localhost

    - name: Check if DeviceWindowsLog configuration needs patching.
      ansible.builtin.template:
        src: tmplt_DeviceWindowsLog.xml.j2
        dest: "{{ winevent_section.dest }}"
      check_mode: true
      delegate_to: localhost
      register: wincollect_needs_patching

    - name: Delete temporary WinEvent XML.
      ansible.builtin.file:
        path: "{{ winevent_section.dest }}"
        state: absent
      changed_when: false
      delegate_to: localhost

    - name: Create patch template.
      become: true
      ansible.windows.win_template:
        src: tmplt_DeviceWindowsLog.xml.j2
        dest: '{{ wincollect_agent_install_dir }}\patch\service_DeviceWindowsLog.xml'
      when: wincollect_needs_patching.changed

- name: Make sure WinCollect is started and set to start automatically.
  become: true
  ansible.windows.win_service:
    name: wincollect
    state: started
    start_mode: auto
