---

- name: Create a temporary file for downloaded package.
  ansible.windows.win_tempfile:
    state: file
  register: temp_file_name

- name: Upload QRadar WinCollect agent installer.
  ansible.windows.win_copy:
    src: "{{ wincollect_agent_7_installer_file }}"
    dest: "{{ temp_file_name.path }}"

- name: Check state of WinCollect service.
  become: true
  ansible.windows.win_service:
    name: wincollect
  failed_when: false
  changed_when: false
  register: wincollect_service_status
  when: wincollect_agent_7_installed_binary.stat.exists | default(false)

- name: Make sure WinCollect is stopped before install.
  become: true
  ansible.windows.win_service:
    name: wincollect
    state: stopped
  when: wincollect_service_status.state | default('') | lower == 'running'

- name: Uninstall WinCollect if installed as managed installation.
  become: true
  ansible.windows.win_package:
    product_id: '{{ wincollect_product_id }}'
    state: absent
    arguments: 'REMOVE_ALL_FILES=True /qn'
  when: wincollect_managed

- name: Install QRadar WinCollect agent.
  become: true
  ansible.windows.win_command: "{{ temp_file_name.path }} {{ wincollect_agent_7_install_parameters }}"
  register: wincollect_agent_7_install
  failed_when: wincollect_agent_7_install.rc != 0
